// Demo seed data for development mode
// These are used for the frontend demo mode only

import { Restaurant, FoodItem } from '../types';
import { FOOD_IMAGES, RESTAURANT_IMAGES } from './images';

export const DEMO_CREDENTIALS = {
  customer: { email: 'customer@futuremeal.in', password: 'Demo@123', name: 'Arjun Sharma' },
  owner: { email: 'owner@futuremeal.in', password: 'Demo@123', name: 'Priya Restaurant' },
  delivery: { email: 'delivery@futuremeal.in', password: 'Demo@123', name: 'Ravi Kumar' },
  admin: { email: 'admin@futuremeal.in', password: 'Demo@123', name: 'Admin User' },
};

export const INDIAN_CITIES = [
  'Hyderabad', 'Bengaluru', 'Chennai', 'Mumbai',
  'Delhi', 'Pune', 'Vijayawada', 'Visakhapatnam', 'Kurnool', 'Tirupati'
];

export const CUISINE_CATEGORIES = [
  { id: 'BIRYANI', name: 'Biryani', emoji: '🍛', color: 'from-amber-400 to-orange-500' },
  { id: 'SOUTH_INDIAN', name: 'South Indian', emoji: '🥘', color: 'from-green-400 to-teal-500' },
  { id: 'NORTH_INDIAN', name: 'North Indian', emoji: '🫓', color: 'from-red-400 to-rose-500' },
  { id: 'STREET_FOOD', name: 'Street Food', emoji: '🥙', color: 'from-yellow-400 to-amber-500' },
  { id: 'HYDERABADI', name: 'Hyderabadi', emoji: '🍲', color: 'from-purple-400 to-indigo-500' },
  { id: 'ANDHRA', name: 'Andhra', emoji: '🌶️', color: 'from-red-500 to-orange-600' },
  { id: 'DESSERTS', name: 'Desserts', emoji: '🍮', color: 'from-pink-400 to-rose-500' },
  { id: 'HEALTHY', name: 'Healthy', emoji: '🥗', color: 'from-lime-400 to-green-500' },
];

export const FEATURED_RESTAURANTS: Partial<Restaurant>[] = [
  {
    id: 1,
    name: 'Spice Route Biryani',
    description: 'Authentic Hyderabadi dum biryani since 1985. Award-winning recipes passed down generations.',
    coverImage: RESTAURANT_IMAGES.biryani_house,
    logo: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=100&q=80',
    cuisines: ['Hyderabadi', 'Biryani', 'Mughlai'],
    rating: 4.6,
    totalReviews: 2841,
    deliveryTime: 30,
    deliveryFee: 30,
    minimumOrder: 149,
    isOpen: true,
    offers: ['20% off on orders above ₹399', 'Free delivery on first order'],
    tags: ['bestseller', 'popular'],
    address: { street: 'Banjara Hills', area: 'Road No 12', city: 'Hyderabad', state: 'Telangana', pincode: '500034' },
    ownerId: 2,
    status: 'ACTIVE',
  },
  {
    id: 2,
    name: 'Annapoorna South Indian',
    description: 'Pure vegetarian South Indian comfort food. Crispy dosas, soft idlis, and authentic sambar.',
    coverImage: RESTAURANT_IMAGES.south_indian_cafe,
    logo: 'https://images.unsplash.com/photo-1630383249896-42f06efd1494?w=100&q=80',
    cuisines: ['South Indian', 'Vegetarian'],
    rating: 4.4,
    totalReviews: 1567,
    deliveryTime: 25,
    deliveryFee: 20,
    minimumOrder: 99,
    isOpen: true,
    offers: ['10% off on all orders'],
    tags: ['pure-veg', 'healthy'],
    address: { street: 'Indiranagar', area: '100 Feet Road', city: 'Bengaluru', state: 'Karnataka', pincode: '560038' },
    ownerId: 3,
    status: 'ACTIVE',
  },
  {
    id: 3,
    name: 'Punjabi Tadka',
    description: 'Rich North Indian curries, freshly baked naans, and classic Punjabi flavors.',
    coverImage: RESTAURANT_IMAGES.dhaba_style,
    logo: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=100&q=80',
    cuisines: ['North Indian', 'Punjabi'],
    rating: 4.3,
    totalReviews: 983,
    deliveryTime: 35,
    deliveryFee: 40,
    minimumOrder: 199,
    isOpen: true,
    offers: ['Buy 1 Get 1 on Butter Naan'],
    tags: ['family-friendly'],
    address: { street: 'Koregaon Park', area: 'Lane 7', city: 'Pune', state: 'Maharashtra', pincode: '411001' },
    ownerId: 4,
    status: 'ACTIVE',
  },
  {
    id: 4,
    name: 'Chaat Corner',
    description: 'Delhi-style chaat and street food favorites. Pani Puri, Pav Bhaji, Samosa Chaat and more.',
    coverImage: RESTAURANT_IMAGES.street_food,
    logo: 'https://images.unsplash.com/photo-1601050690117-94f5f6fa8bd7?w=100&q=80',
    cuisines: ['Street Food', 'Chaat', 'Snacks'],
    rating: 4.5,
    totalReviews: 2103,
    deliveryTime: 20,
    deliveryFee: 15,
    minimumOrder: 79,
    isOpen: true,
    offers: ['Free Masala Papad on every order'],
    tags: ['budget', 'quick'],
    address: { street: 'Connaught Place', area: 'Inner Circle', city: 'Delhi', state: 'Delhi', pincode: '110001' },
    ownerId: 5,
    status: 'ACTIVE',
  },
];

export const POPULAR_FOODS: Partial<FoodItem>[] = [
  {
    id: 1,
    name: 'Chicken Dum Biryani',
    description: 'Slow-cooked aromatic Hyderabadi biryani with tender chicken, saffron rice, and fried onions.',
    image: FOOD_IMAGES.chicken_biryani,
    price: 229,
    originalPrice: 299,
    category: 'Biryani',
    restaurantId: 1,
    restaurantName: 'Spice Route Biryani',
    dietaryType: 'NON_VEG',
    spiceLevel: 'MEDIUM',
    rating: 4.7,
    totalReviews: 1243,
    preparationTime: 25,
    isAvailable: true,
    isBestseller: true,
    isRecommended: true,
  },
  {
    id: 2,
    name: 'Masala Dosa',
    description: 'Crispy golden dosa with spiced potato filling, served with coconut chutney and sambar.',
    image: FOOD_IMAGES.masala_dosa,
    price: 89,
    category: 'South Indian',
    restaurantId: 2,
    restaurantName: 'Annapoorna South Indian',
    dietaryType: 'VEG',
    spiceLevel: 'MILD',
    rating: 4.5,
    totalReviews: 867,
    preparationTime: 15,
    isAvailable: true,
    isBestseller: true,
    isRecommended: false,
  },
  {
    id: 3,
    name: 'Butter Chicken',
    description: 'Tender chicken in rich tomato-cream sauce, slow-cooked with aromatic spices.',
    image: FOOD_IMAGES.butter_chicken,
    price: 249,
    originalPrice: 299,
    category: 'North Indian',
    restaurantId: 3,
    restaurantName: 'Punjabi Tadka',
    dietaryType: 'NON_VEG',
    spiceLevel: 'MEDIUM',
    rating: 4.6,
    totalReviews: 743,
    preparationTime: 20,
    isAvailable: true,
    isBestseller: true,
    isRecommended: true,
  },
  {
    id: 4,
    name: 'Pani Puri (8 Pcs)',
    description: 'Crispy hollow puris filled with spiced tamarind water, potato, and chickpeas.',
    image: FOOD_IMAGES.pani_puri,
    price: 59,
    category: 'Street Food',
    restaurantId: 4,
    restaurantName: 'Chaat Corner',
    dietaryType: 'VEG',
    spiceLevel: 'SPICY',
    rating: 4.4,
    totalReviews: 1102,
    preparationTime: 10,
    isAvailable: true,
    isBestseller: false,
    isRecommended: true,
  },
  {
    id: 5,
    name: 'Mutton Biryani',
    description: 'Slow-cooked mutton with fragrant basmati rice and whole spices.',
    image: FOOD_IMAGES.mutton_biryani,
    price: 299,
    category: 'Biryani',
    restaurantId: 1,
    restaurantName: 'Spice Route Biryani',
    dietaryType: 'NON_VEG',
    spiceLevel: 'SPICY',
    rating: 4.8,
    totalReviews: 892,
    preparationTime: 35,
    isAvailable: true,
    isBestseller: true,
    isRecommended: false,
  },
  {
    id: 6,
    name: 'Paneer Butter Masala',
    description: 'Soft paneer cubes in a rich, creamy tomato-cashew gravy.',
    image: FOOD_IMAGES.paneer_butter_masala,
    price: 199,
    category: 'North Indian',
    restaurantId: 3,
    restaurantName: 'Punjabi Tadka',
    dietaryType: 'VEG',
    spiceLevel: 'MILD',
    rating: 4.5,
    totalReviews: 612,
    preparationTime: 18,
    isAvailable: true,
    isBestseller: false,
    isRecommended: true,
  },
];

export const TESTIMONIALS = [
  {
    id: 1,
    name: 'Meera Nair',
    city: 'Bengaluru',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&q=80',
    rating: 5,
    comment: 'FutureMeal is genius. I planned my post-gym meal two days in advance and got exactly what I wanted at the right time. The recommendation was spot on!',
    feature: 'FutureMeal',
  },
  {
    id: 2,
    name: 'Rohit Verma',
    city: 'Hyderabad',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80',
    rating: 5,
    comment: 'Best biryani delivery app in Hyderabad. The Spice Route biryani is phenomenal and always arrives hot.',
    feature: 'Food Quality',
  },
  {
    id: 3,
    name: 'Kavitha Reddy',
    city: 'Vijayawada',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80',
    rating: 5,
    comment: 'I love that I can plan meals in advance without worrying about it. FutureMeal reminded me of my dinner plan and everything was sorted!',
    feature: 'FutureMeal',
  },
  {
    id: 4,
    name: 'Arjun Patel',
    city: 'Mumbai',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80',
    rating: 4,
    comment: 'Clean UI, fast delivery, and great restaurant selection. The cart experience is the smoothest I have used.',
    feature: 'App Experience',
  },
];
